global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1) Prometheus însuși (ca să vezi că merge)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: 'login-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '192.168.1.138:8000' ]  # macOS Podman: use your host IP